#!/usr/bin/env python3
"""
Notification System for Clinical Trial Site Analysis Platform
Sends notifications for pipeline events and alerts
"""
import sys
import os
import smtplib
import json
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Dict, List, Optional

# Add the project root to the Python path
sys.path.append(os.path.dirname(os.path.abspath(__file__)) + "/../")

class NotificationSystem:
    """System for sending notifications and alerts"""
    
    def __init__(self, config_file: str = "../config.json"):
        """
        Initialize the notification system
        
        Args:
            config_file: Path to configuration file
        """
        self.config = self.load_config(config_file)
        self.notifications_enabled = self.config.get("notifications_enabled", False)
        self.email_config = self.config.get("email", {})
    
    def load_config(self, config_file: str) -> Dict:
        """
        Load configuration from file
        
        Args:
            config_file: Path to configuration file
            
        Returns:
            Configuration dictionary
        """
        try:
            with open(config_file, 'r') as f:
                return json.load(f)
        except FileNotFoundError:
            print(f"Configuration file {config_file} not found, using defaults")
            return {}
        except json.JSONDecodeError:
            print(f"Invalid JSON in configuration file {config_file}, using defaults")
            return {}
    
    def send_email_notification(self, subject: str, body: str, recipients: List[str]) -> bool:
        """
        Send email notification
        
        Args:
            subject: Email subject
            body: Email body
            recipients: List of recipient email addresses
            
        Returns:
            True if successful, False otherwise
        """
        if not self.notifications_enabled:
            print("Notifications are disabled")
            return False
            
        try:
            # Create message
            msg = MIMEMultipart()
            msg['From'] = self.email_config.get("sender", "no-reply@clinical-trials-platform.com")
            msg['To'] = ", ".join(recipients)
            msg['Subject'] = subject
            
            # Add body
            msg.attach(MIMEText(body, 'plain'))
            
            # Send email
            server = smtplib.SMTP(
                self.email_config.get("smtp_server", "localhost"),
                self.email_config.get("smtp_port", 587)
            )
            server.starttls()
            server.login(
                self.email_config.get("username", ""),
                self.email_config.get("password", "")
            )
            server.send_message(msg)
            server.quit()
            
            print(f"Email notification sent to {', '.join(recipients)}")
            return True
            
        except Exception as e:
            print(f"Error sending email notification: {e}")
            return False
    
    def send_pipeline_completion_notification(self, success: bool, duration: float, 
                                            records_processed: int, errors: List[str] = None) -> bool:
        """
        Send pipeline completion notification
        
        Args:
            success: Whether pipeline completed successfully
            duration: Pipeline execution duration in seconds
            records_processed: Number of records processed
            errors: List of errors encountered (if any)
            
        Returns:
            True if successful, False otherwise
        """
        recipients = self.config.get("notification_recipients", [])
        if not recipients:
            print("No notification recipients configured")
            return False
        
        # Create subject
        status = "SUCCESS" if success else "FAILURE"
        subject = f"Clinical Trial Pipeline {status} - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        
        # Create body
        body = f"""
Clinical Trial Data Pipeline Completion Report
============================================

Status: {status}
Execution Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Duration: {duration:.2f} seconds
Records Processed: {records_processed}

"""
        
        if success:
            body += "Pipeline completed successfully with no errors.\n"
        else:
            body += "Pipeline failed with the following errors:\n"
            if errors:
                for error in errors:
                    body += f"  - {error}\n"
            else:
                body += "  - Unknown error\n"
        
        body += f"\nGenerated by Clinical Trial Site Analysis Platform\n"
        
        return self.send_email_notification(subject, body, recipients)
    
    def send_data_quality_alert(self, issues: Dict[str, any]) -> bool:
        """
        Send data quality alert notification
        
        Args:
            issues: Dictionary with data quality issues
            
        Returns:
            True if successful, False otherwise
        """
        recipients = self.config.get("notification_recipients", [])
        if not recipients:
            print("No notification recipients configured")
            return False
        
        subject = f"Data Quality Alert - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        
        body = f"""
Data Quality Alert
==================

Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

Issues Detected:
"""
        
        for issue_type, issue_details in issues.items():
            body += f"\n{issue_type.upper()}:\n"
            if isinstance(issue_details, dict) and 'count' in issue_details:
                body += f"  Count: {issue_details['count']}\n"
                if 'details' in issue_details and issue_details['details']:
                    body += "  Details:\n"
                    for detail in issue_details['details'][:5]:  # Limit to first 5
                        body += f"    - {detail}\n"
                    if len(issue_details['details']) > 5:
                        body += f"    ... and {len(issue_details['details']) - 5} more\n"
            else:
                body += f"  {issue_details}\n"
        
        body += f"\nPlease review the data quality report for more details.\n"
        body += f"\nGenerated by Clinical Trial Site Analysis Platform\n"
        
        return self.send_email_notification(subject, body, recipients)
    
    def send_system_alert(self, alert_type: str, message: str, severity: str = "medium") -> bool:
        """
        Send system alert notification
        
        Args:
            alert_type: Type of alert
            message: Alert message
            severity: Alert severity (low, medium, high, critical)
            
        Returns:
            True if successful, False otherwise
        """
        recipients = self.config.get("notification_recipients", [])
        if not recipients:
            print("No notification recipients configured")
            return False
        
        severity_emoji = {
            "low": "ℹ️",
            "medium": "⚠️",
            "high": "🚨",
            "critical": "🔥"
        }
        
        subject = f"{severity_emoji.get(severity, '⚠️')} System Alert: {alert_type} - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        
        body = f"""
System Alert
============

Type: {alert_type}
Severity: {severity.upper()}
Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

Message:
{message}

Generated by Clinical Trial Site Analysis Platform
"""
        
        return self.send_email_notification(subject, body, recipients)

def main():
    """Main function for testing"""
    notification_system = NotificationSystem()
    
    # Test pipeline completion notification
    print("Testing pipeline completion notification...")
    success = notification_system.send_pipeline_completion_notification(
        success=True,
        duration=125.5,
        records_processed=42,
        errors=[]
    )
    
    if success:
        print("Pipeline completion notification sent successfully!")
    else:
        print("Failed to send pipeline completion notification")
    
    # Test data quality alert
    print("\nTesting data quality alert...")
    issues = {
        "duplicate_sites": {
            "count": 3,
            "details": ["Site A", "Site B", "Site C"]
        },
        "missing_data": "15% of records have missing information"
    }
    
    success = notification_system.send_data_quality_alert(issues)
    
    if success:
        print("Data quality alert sent successfully!")
    else:
        print("Failed to send data quality alert")
    
    # Test system alert
    print("\nTesting system alert...")
    success = notification_system.send_system_alert(
        alert_type="Database Connection",
        message="Database connection lost for 30 seconds",
        severity="high"
    )
    
    if success:
        print("System alert sent successfully!")
    else:
        print("Failed to send system alert")

if __name__ == "__main__":
    main()